# ANALISIS DATOS : HEART FAILURE PREDICTION

## 1. CARGA DE DATOS

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# lectura de datos en Python
heart = pd.read_csv('./../heart/heart.csv')

## 2. Explorar datos (EDA)

In [3]:
heart.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='str')

In [ ]:
heart.shape

In [ ]:
heart.info()

In [6]:
heart.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [ ]:
pd.read_csv('./../heart/heart.csv')

In [ ]:
heart.min()

Age                 28
Sex                  F
ChestPainType      ASY
RestingBP           80
Cholesterol         85
FastingBS            0
RestingECG         LVH
MaxHR               60
ExerciseAngina       N
Oldpeak           -2.6
ST_Slope          Down
HeartDisease         0
dtype: object

In [ ]:
heart.max()

Age                77
Sex                 1
ChestPainType       3
RestingBP         200
Cholesterol       603
FastingBS           1
RestingECG          2
MaxHR             202
ExerciseAngina      1
Oldpeak           6.2
ST_Slope           Up
HeartDisease        1
dtype: object

In [ ]:
df_heart = pd.DataFrame(heart, columns=['Age','Sex','ChestPainType','RestingBP','Cholesterol','FastingBS','RestingECG','MaxHR','ExerciseAngina','Oldpeak'])
df_heart

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak
0,40,1,0,140,289,0,0,172,0,0.0
1,49,0,1,160,180,0,0,156,0,1.0
2,37,1,0,130,283,0,1,98,0,0.0
3,48,0,2,138,214,0,0,108,1,1.5
4,54,1,1,150,195,0,0,122,0,0.0
...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,0,132,0,1.2
914,68,1,2,144,193,1,0,141,0,3.4
915,57,1,2,130,131,0,0,115,1,1.2
916,57,0,0,130,236,0,2,174,0,0.0
917,38,1,1,138,175,0,0,173,0,0.0

In [ ]:
df_heart.mean()

Age                53.510893
Sex                 0.789760
ChestPainType       1.452070
RestingBP         132.540305
Cholesterol       244.516340
FastingBS           0.233115
RestingECG          0.603486
MaxHR             136.809368
ExerciseAngina      0.404139
Oldpeak             0.887364
dtype: float64

## 3. PRE-PROCESSING

### 3.1 Fixing Problems

In [ ]:
plt.bar(heart['Age'], heart['Cholesterol'])
plt.show()

In [ ]:
heart[heart['Cholesterol']==0]

In [ ]:
heart[heart['RestingBP']==0]

In [ ]:
len(heart[heart['Cholesterol']==0])

0

In [ ]:
len(heart[heart['RestingBP']==0])

0

In [ ]:
# Calcular la media de Cholesterol excluyendo los ceros.
# Pista: filtra primero las filas donde 
# Cholesterol es distinto de 0 con != y luego aplica .mean()

In [ ]:
heart[heart['Cholesterol']!=0]['Cholesterol'].mean()

np.float64(244.6353887399464)

In [ ]:
heart.loc[heart['Cholesterol']==0,'Cholesterol'] = 244

In [ ]:
heart[heart['RestingBP']!=0]['RestingBP'].mean()

np.float64(132.54089422028352)

In [ ]:
heart.loc[heart['RestingBP']==0,'RestingBP'] = 132

In [ ]:
len(heart[heart['Cholesterol']==0])

0

In [ ]:
heart[heart['Cholesterol']==0].head()

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

### 3.2 ENCODING

In [26]:
heart['Sex'] = heart['Sex'].map({'M':1, 'F':0}).astype(int)

In [27]:
heart['ChestPainType'] = heart['ChestPainType'].map({'ATA':0, 'NAP':1, 'ASY':2, 'TA':3}).astype(int)

In [28]:
heart['RestingECG'] = heart['RestingECG'].map({'Normal':0, 'ST':1, 'LVH':2}).astype(int)

In [29]:
heart['ExerciseAngina'] = heart['ExerciseAngina'].map({'N':0, 'Y':1}).astype(int)

In [5]:
heart.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0