# PROYECTO ML - CiberSeguridad

- Transformar CSV wednesday.csv a uno con las columnas necesarias que quiero

# PROYECTO ML - CiberSeguridad

- Transformar CSV wednesday.csv a uno con las columnas necesarias que quiero

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
lista_cs = pd.read_csv('wednesday.csv')

In [6]:
lista_cs.columns

Index(['id', 'Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol',
       'Timestamp', 'Flow Duration', 'Total Fwd Packet', 'Total Bwd packets',
       'Total Length of Fwd Packet', 'Total Length of Bwd Packet',
       'Fwd Packet Length Max', 'Fwd Packet Length Min',
       'Fwd Packet Length Mean', 'Fwd Packet Length Std',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags',
       'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd RST Flags',
       'Bwd RST Flags', 'Fwd Header Length', 'Bwd Header Length',
       'Fwd Packets/s', 'Bwd Packets/s', 'Packet Length Min',
       'Packet Length Max', 'Packet Length Mean', 'Packet Length Std',
       'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count',
       'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count',
       'CWR Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Fwd Segment Size Avg', 'Bwd Segment Size Avg',
       'Fwd Bytes/Bulk Avg', 'Fwd Packet/Bulk Avg', 'Fwd Bulk Rate Avg',
       'Bwd Bytes/Bulk Avg', 'Bwd Packet/Bulk Avg', 'Bwd Bulk Rate Avg',
       'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets',
       'Subflow Bwd Bytes', 'FWD Init Win Bytes', 'Bwd Init Win Bytes',
       'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std',
       'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max',
       'Idle Min', 'ICMP Code', 'ICMP Type', 'Total TCP Flow Time', 'Label',
       'Attempted Category'],
      dtype='str')

In [7]:
lista_cs.info()

<class 'pandas.DataFrame'>
RangeIndex: 496641 entries, 0 to 496640
Data columns (total 91 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          496641 non-null  int64
 1   Flow ID                     496641 non-null  str
 2   Src IP                      496641 non-null  str
 3   Src Port                    496641 non-null  int64
 4   Dst IP                      496641 non-null  str
 5   Dst Port                    496641 non-null  int64
 6   Protocol                    496641 non-null  int64
 7   Timestamp                   496641 non-null  str
 8   Flow Duration               496641 non-null  int64
 9   Total Fwd Packet            496641 non-null  int64
 10  Total Bwd packets           496641 non-null  int64
 11  Total Length of Fwd Packet  496641 non-null  int64
 12  Total Length of Bwd Packet  496641 non-null  int64
 13  Fwd Packet Length Max       496641 non-null  int64
 14  Fwd Packet Length Min       496641 non-null  int64
 15  Fwd Packet Length Mean      496641 non-null  float64
 16  Fwd Packet Length Std       496641 non-null  float64
 17  Bwd Packet Length Max       496641 non-null  int64
 18  Bwd Packet Length Min       496641 non-null  int64
 19  Bwd Packet Length Mean      496641 non-null  float64
 20  Bwd Packet Length Std       496641 non-null  float64
 21  Flow Bytes/s                496641 non-null  float64
 22  Flow Packets/s              496641 non-null  float64
 23  Flow IAT Mean               496641 non-null  float64
 24  Flow IAT Std                496641 non-null  float64
 25  Flow IAT Max                496641 non-null  int64
 26  Flow IAT Min                496641 non-null  int64
 27  Fwd IAT Total               496641 non-null  int64
 28  Fwd IAT Mean                496641 non-null  float64
 29  Fwd IAT Std                 496641 non-null  float64
 30  Fwd IAT Max                 496641 non-null  int64
 31  Fwd IAT Min                 496641 non-null  int64
 32  Bwd IAT Total               496641 non-null  int64
 33  Bwd IAT Mean                496641 non-null  float64
 34  Bwd IAT Std                 496641 non-null  float64
 35  Bwd IAT Max                 496641 non-null  int64
 36  Bwd IAT Min                 496641 non-null  int64
 37  Fwd PSH Flags               496641 non-null  int64
 38  Bwd PSH Flags               496641 non-null  int64
 39  Fwd URG Flags               496641 non-null  int64
 40  Bwd URG Flags               496641 non-null  int64
 41  Fwd RST Flags               496641 non-null  int64
 42  Bwd RST Flags               496641 non-null  int64
 43  Fwd Header Length           496641 non-null  int64
 44  Bwd Header Length           496641 non-null  int64
 45  Fwd Packets/s               496641 non-null  float64
 46  Bwd Packets/s               496641 non-null  float64
 47  Packet Length Min           496641 non-null  int64
 48  Packet Length Max           496641 non-null  int64
 49  Packet Length Mean          496641 non-null  float64
 50  Packet Length Std           496641 non-null  float64
 51  Packet Length Variance      496641 non-null  float64
 52  FIN Flag Count              496641 non-null  int64
 53  SYN Flag Count              496641 non-null  int64
 54  RST Flag Count              496641 non-null  int64
 55  PSH Flag Count              496641 non-null  int64
 56  ACK Flag Count              496641 non-null  int64
 57  URG Flag Count              496641 non-null  int64
 58  CWR Flag Count              496641 non-null  int64
 59  ECE Flag Count              496641 non-null  int64
 60  Down/Up Ratio               496641 non-null  float64
 61  Average Packet Size         496641 non-null  float64
 62  Fwd Segment Size Avg        496641 non-null  float64
 63  Bwd Segment Size Avg        496641 non-null  float64
 64  Fwd Bytes/Bulk Avg          496641 non-null  int64
 65  Fwd Packet/Bulk Avg         496641 non-null  int64
 66  Fwd Bulk Rate Avg           496641 non-null  int64
 67  Bwd Bytes/Bulk Avg          496641 non-null  int64
 68  Bwd Packet/Bulk Avg         496641 non-null  int64
 69  Bwd Bulk Rate Avg           496641 non-null  int64
 70  Subflow Fwd Packets         496641 non-null  int64
 71  Subflow Fwd Bytes           496641 non-null  int64
 72  Subflow Bwd Packets         496641 non-null  int64
 73  Subflow Bwd Bytes           496641 non-null  int64
 74  FWD Init Win Bytes          496641 non-null  int64
 75  Bwd Init Win Bytes          496641 non-null  int64
 76  Fwd Act Data Pkts           496641 non-null  int64
 77  Fwd Seg Size Min            496641 non-null  int64
 78  Active Mean                 496641 non-null  float64
 79  Active Std                  496641 non-null  float64
 80  Active Max                  496641 non-null  int64
 81  Active Min                  496641 non-null  int64
 82  Idle Mean                   496641 non-null  float64
 83  Idle Std                    496641 non-null  float64
 84  Idle Max                    496641 non-null  int64
 85  Idle Min                    496641 non-null  int64
 86  ICMP Code                   496641 non-null  int64
 87  ICMP Type                   496641 non-null  int64
 88  Total TCP Flow Time         496641 non-null  int64
 89  Label                       496641 non-null  str
 90  Attempted Category          496641 non-null  int64
dtypes: float64(25), int64(61), str(5)
memory usage: 344.8 MB

In [8]:
df_cibseg = pd.DataFrame(lista_cs)
df_cibseg

,id,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Total Fwd Packet,...,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,ICMP Code,ICMP Type,Total TCP Flow Time,Label,Attempted Category
0,1,192.168.10.9-52.197.242.182-13793-443-6,192.168.10.9,13793,52.197.242.182,443,6,2017-07-05 11:43:34.783702,187889,1,...,0,0.00,0.000000e+00,0,0,-1,-1,187889,BENIGN,-1
1,2,192.168.10.9-52.197.242.182-13793-443-6,192.168.10.9,13793,52.197.242.182,443,6,2017-07-05 11:43:35.484765,187758,1,...,0,0.00,0.000000e+00,0,0,-1,-1,187758,BENIGN,-1
2,3,192.168.10.9-54.65.28.113-13794-443-6,192.168.10.9,13794,54.65.28.113,443,6,2017-07-05 11:43:36.375217,189882,1,...,0,0.00,0.000000e+00,0,0,-1,-1,189882,BENIGN,-1
3,4,192.168.10.9-54.65.28.113-13794-443-6,192.168.10.9,13794,54.65.28.113,443,6,2017-07-05 11:43:37.075970,190117,1,...,0,0.00,0.000000e+00,0,0,-1,-1,190117,BENIGN,-1
4,5,192.168.10.9-52.197.242.182-13796-443-6,192.168.10.9,13796,52.197.242.182,443,6,2017-07-05 11:43:37.968708,188603,1,...,0,0.00,0.000000e+00,0,0,-1,-1,188603,BENIGN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496636,496637,192.168.10.8-198.51.152.183-59942-80-6,192.168.10.8,59942,198.51.152.183,80,6,2017-07-05 17:50:58.592115,5074745,7,...,0,0.00,0.000000e+00,0,0,-1,-1,5074745,BENIGN,-1
496637,496638,192.168.10.16-192.168.10.3-27998-53-17,192.168.10.16,27998,192.168.10.3,53,17,2017-07-05 13:03:34.820723,209,2,...,0,0.00,0.000000e+00,0,0,-1,-1,0,BENIGN,-1
496638,496639,192.168.10.51-23.208.163.130-58030-443-6,192.168.10.51,58030,23.208.163.130,443,6,2017-07-05 13:04:59.752472,116281383,24,...,23012,9639209.75,1.321437e+06,10024910,5443180,-1,-1,116281383,BENIGN,-1
496639,496640,192.168.10.5-192.168.10.3-51818-53-17,192.168.10.5,51818,192.168.10.3,53,17,2017-07-05 18:20:02.014027,149,2,...,0,0.00,0.000000e+00,0,0,-1,-1,0,BENIGN,-1
496640,496641,192.168.10.15-192.168.10.3-55355-53-17,192.168.10.15,55355,192.168.10.3,53,17,2017-07-05 14:59:58.680504,61066,4,...,0,0.00,0.000000e+00,0,0,-1,-1,0,BENIGN,-1

In [9]:
df_cibseg.drop(columns=['id','Flow ID','Src IP','Src Port','Dst IP','Dst Port','Protocol','Timestamp','Attempted Category'], inplace=True) 
df_cibseg.to_csv('wednesday_clean.csv', index=False)

In [10]:
print(df_cibseg.shape)
print(df_cibseg.columns)

(496641, 82)
Index(['Flow Duration', 'Total Fwd Packet', 'Total Bwd packets',
       'Total Length of Fwd Packet', 'Total Length of Bwd Packet',
       'Fwd Packet Length Max', 'Fwd Packet Length Min',
       'Fwd Packet Length Mean', 'Fwd Packet Length Std',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags',
       'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd RST Flags',
       'Bwd RST Flags', 'Fwd Header Length', 'Bwd Header Length',
       'Fwd Packets/s', 'Bwd Packets/s', 'Packet Length Min',
       'Packet Length Max', 'Packet Length Mean', 'Packet Length Std',
       'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count',
       'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count',
       'CWR Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Fwd Segment Size Avg', 'Bwd Segment Size Avg',
       'Fwd Bytes/Bulk Avg', 'Fwd Packet/Bulk Avg', 'Fwd Bulk Rate Avg',
       'Bwd Bytes/Bulk Avg', 'Bwd Packet/Bulk Avg', 'Bwd Bulk Rate Avg',
       'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets',
       'Subflow Bwd Bytes', 'FWD Init Win Bytes', 'Bwd Init Win Bytes',
       'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std',
       'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max',
       'Idle Min', 'ICMP Code', 'ICMP Type', 'Total TCP Flow Time', 'Label'],
      dtype='str')

In [11]:
df_cibseg

,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,Total Length of Bwd Packet,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,...,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,ICMP Code,ICMP Type,Total TCP Flow Time,Label
0,187889,1,1,0,0,0,0,0.000000,0.000000,0,...,0,0,0.00,0.000000e+00,0,0,-1,-1,187889,BENIGN
1,187758,1,1,0,0,0,0,0.000000,0.000000,0,...,0,0,0.00,0.000000e+00,0,0,-1,-1,187758,BENIGN
2,189882,1,1,0,0,0,0,0.000000,0.000000,0,...,0,0,0.00,0.000000e+00,0,0,-1,-1,189882,BENIGN
3,190117,1,1,0,0,0,0,0.000000,0.000000,0,...,0,0,0.00,0.000000e+00,0,0,-1,-1,190117,BENIGN
4,188603,1,1,0,0,0,0,0.000000,0.000000,0,...,0,0,0.00,0.000000e+00,0,0,-1,-1,188603,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496636,5074745,7,6,582,1204,582,0,83.142857,219.975323,602,...,0,0,0.00,0.000000e+00,0,0,-1,-1,5074745,BENIGN
496637,209,2,2,70,230,35,35,35.000000,0.000000,115,...,0,0,0.00,0.000000e+00,0,0,-1,-1,0,BENIGN
496638,116281383,24,21,699,5411,322,0,29.125000,79.231808,1448,...,328226,23012,9639209.75,1.321437e+06,10024910,5443180,-1,-1,116281383,BENIGN
496639,149,2,2,72,104,36,36,36.000000,0.000000,52,...,0,0,0.00,0.000000e+00,0,0,-1,-1,0,BENIGN
496640,61066,4,2,152,244,38,38,38.000000,0.000000,122,...,0,0,0.00,0.000000e+00,0,0,-1,-1,0,BENIGN

In [12]:
df_cibseg.isnull().sum()

Flow Duration                 0
Total Fwd Packet              0
Total Bwd packets             0
Total Length of Fwd Packet    0
Total Length of Bwd Packet    0
                             ..
Idle Min                      0
ICMP Code                     0
ICMP Type                     0
Total TCP Flow Time           0
Label                         0
Length: 82, dtype: int64

In [13]:
numericas = df_cibseg.select_dtypes(include=['int64', 'float64'])
np.isinf(numericas).sum()

Flow Duration                 0
Total Fwd Packet              0
Total Bwd packets             0
Total Length of Fwd Packet    0
Total Length of Bwd Packet    0
                             ..
Idle Max                      0
Idle Min                      0
ICMP Code                     0
ICMP Type                     0
Total TCP Flow Time           0
Length: 81, dtype: int64

In [14]:
df_cibseg.min()

Flow Duration                      0
Total Fwd Packet                   0
Total Bwd packets                  0
Total Length of Fwd Packet         0
Total Length of Bwd Packet         0
                               ...
Idle Min                           0
ICMP Code                         -1
ICMP Type                         -1
Total TCP Flow Time                0
Label                         BENIGN
Length: 82, dtype: object

In [15]:
numericas.std()

c:\Users\Lucci\Desktop\Practicas_UPV\.venv\Lib\site-packages\pandas\core\nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

Flow Duration                 3.078211e+07
Total Fwd Packet              8.824252e+02
Total Bwd packets             1.162333e+03
Total Length of Fwd Packet    4.791593e+03
Total Length of Bwd Packet    2.646551e+06
                                  ...
Idle Max                      1.539773e+07
Idle Min                      1.393293e+07
ICMP Code                     2.887176e-02
ICMP Type                     4.073184e-02
Total TCP Flow Time           4.203989e+08
Length: 81, dtype: float64

In [16]:
df_cibseg.value_counts()

Flow Duration  Total Fwd Packet  Total Bwd packets  Total Length of Fwd Packet  Total Length of Bwd Packet  Fwd Packet Length Max  Fwd Packet Length Min  Fwd Packet Length Mean  Fwd Packet Length Std  Bwd Packet Length Max  Bwd Packet Length Min  Bwd Packet Length Mean  Bwd Packet Length Std  Flow Bytes/s  Flow Packets/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Total  Fwd IAT Mean  Fwd IAT Std   Fwd IAT Max  Fwd IAT Min  Bwd IAT Total  Bwd IAT Mean  Bwd IAT Std   Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd RST Flags  Bwd RST Flags  Fwd Header Length  Bwd Header Length  Fwd Packets/s   Bwd Packets/s  Packet Length Min  Packet Length Max  Packet Length Mean  Packet Length Std  Packet Length Variance  FIN Flag Count  SYN Flag Count  RST Flag Count  PSH Flag Count  ACK Flag Count  URG Flag Count  CWR Flag Count  ECE Flag Count  Down/Up Ratio  Average Packet Size  Fwd Segment Size Avg  Bwd Segment Size Avg  Fwd Bytes/Bulk Avg  Fwd Packet/Bulk Avg  Fwd Bulk Rate Avg  Bwd Bytes/Bulk Avg  Bwd Packet/Bulk Avg  Bwd Bulk Rate Avg  Subflow Fwd Packets  Subflow Fwd Bytes  Subflow Bwd Packets  Subflow Bwd Bytes  FWD Init Win Bytes  Bwd Init Win Bytes  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std    Active Max  Active Min  Idle Mean   Idle Std      Idle Max  Idle Min  ICMP Code  ICMP Type  Total TCP Flow Time  Label
3              2                 0                  124                         0                           62                     62                     62.000000               0.000000               0                      0                      0.000000                0.000000               4.133333e+07  666666.666667   3.000000e+00   0.000000e+00  3             3             3              3.000000e+00  0.000000e+00  3            3            0              0.00          0.000000e+00  0            0            0              0              0              0              0              0              16                 0                  666666.666667   0.000000       62                 62                 62.000000           0.000000           0.000000                0               0               0               0               0               0               0               0               0.000000       62.000000            62.000000             0.000000              0                   0                    0                  0                   0                    0                  1                    62                 0                    0                  0                   0                   1                  8                 0.0          0.000000      0           0           0.00        0.000000e+00  0         0         -1         -1         0                    BENIGN    286
4              2                 0                  124                         0                           62                     62                     62.000000               0.000000               0                      0                      0.000000                0.000000               3.100000e+07  500000.000000   4.000000e+00   0.000000e+00  4             4             4              4.000000e+00  0.000000e+00  4            4            0              0.00          0.000000e+00  0            0            0              0              0              0              0              0              16                 0                  500000.000000   0.000000       62                 62                 62.000000           0.000000           0.000000                0               0               0               0               0               0               0               0               0.000000       62.000000            62.000000             0.000000              0                   0                    0                  0                   0                    0                  1                    62                 0                    0                  0                   0                   1                  8                 0.0          0.000000      0           0           0.00        0.000000e+00  0         0         -1         -1         0                    BENIGN    149
48             2                 0                  124                         0                           62                     62                     62.000000               0.000000               0                      0                      0.000000                0.000000               2.583333e+06  41666.666667    4.800000e+01   0.000000e+00  48            48            48             4.800000e+01  0.000000e+00  48           48           0              0.00          0.000000e+00  0            0            0              0              0              0              0              0              16                 0                  41666.666667    0.000000       62                 62                 62.000000           0.000000           0.000000                0               0               0               0               0               0               0               0               0.000000       62.000000            62.000000             0.000000              0                   0                    0                  0                   0                    0                  1                    62                 0                    0                  0                   0                   1                  8                 0.0          0.000000      0           0           0.00        0.000000e+00  0         0         -1         -1         0                    BENIGN     69
21             13                0                  650                         0                           50                     50                     50.000000               0.000000               0                      0                      0.000000                0.000000               3.095238e+07  619047.619048   1.750000e+00   1.712255e+00  7             1             21             1.750000e+00  1.712255e+00  7            1            0              0.00          0.000000e+00  0            0            0              0              0              0              0              0              104                0                  619047.619048   0.000000       50                 50                 50.000000           0.000000           0.000000                0               0               0               0               0               0               0               0               0.000000       50.000000            50.000000             0.000000              650                 13                   30952380           0                   0                    0                  1                    50                 0                    0                  0                   0                   12                 8                 0.0          0.000000      0           0           0.00        0.000000e+00  0         0         -1         -1         0                    BENIGN     64
2              2                 0                  124                         0                           62                     62                     62.000000               0.000000               0                      0                      0.000000                0.000000               6.200000e+07  1000000.000000  2.000000e+00   0.000000e+00  2             2             2              2.000000e+00  0.000000e+00  2            2            0              0.00          0.000000e+00  0            0            0              0              0              0              0              0              16                 0                  1000000.000000  0.000000       62                 62                 62.000000           0.000000           0.000000                0               0               0               0               0               0               0               0               0.000000       62.000000            62.000000             0.000000              0                   0                    0                  0                   0                    0                  1                    62                 0                    0                  0                   0                   1                  8                 0.0          0.000000      0           0           0.00        0.000000e+00  0         0         -1         -1         0                    BENIGN     61
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ...
47207          2                 2                  60                          264                         30                     30                     30.000000               0.000000               132                    132                    132.000000              0.000000               6.863389e+03  84.733196       1.573567e+04   2.717097e+04  47110         48            48             4.800000e+01  0.000000e+00  48           48           49             49.00         0.000000e+00  49           49           0              0              0              0              0              0              16                 16                 42.366598       42.366598      30                 132                81.000000           58.889727          3468.000000             0               0               0               0               0               0               0               0               1.000000       81.000000            30.000000             132.000000            0                   0                    0                  0                   0                    0                  0                    15                 0                    66                 0                   0                   1                  8                 0.0          0.000000      0           0           0.00        0.000000e+00  0         0         -1         -1         0                    BENIGN      1
5074745        7                 6                  582                         1204                        582                    0                      83.142857               219.975323             602                    0                      200.666667              310.871463             3.519389e+02  2.561705        4.228954e+05   1.372437e+06  4777399       3             5051151        8.418585e+05  1.929960e+06  4777416      76           5050855        1010171.00    2.107843e+06  4777403      3287         1              2              0              0              0              0              152                128                1.379380        1.182325       0                  602                137.384615          261.113493         68180.256410            2               2               0               3               12              0               0               0               0.857143       137.384615           83.142857             200.666667            0                   0                    0                  0                   0                    0                  0                    44                 0                    92                 8192                23                  1                  20                0.0          0.000000      0           0           0.00        0.000000e+00  0         0         -1         -1         5074745              BENIGN      1
209            2                 2                  70                          230                         35                     35                     35.000000               0.000000               115                    115                    115.000000              0.000000               1.435407e+06  19138.755981    6.966667e+01   1.146051e+02  202           3             4              4.000000e+00  0.000000e+00  4            4            3              3.00          0.000000e+00  3            3            0              0              0              0              0              0              16                 16                 9569.377990     9569.377990    35                 115                75.000000           46.188022          2133.333333             0               0               0               0               0               0               0               0               1.000000       75.000000            35.000000             115.000000            0                   0                    0                  0                   0                    0                  0                    17                 0                    57                 0                   0                   1                  8                 0.0          0.000000      0           0           0.00        0.000000e+00  0         0         -1         -1         0                    BENIGN      1
116281383      24                21                 699                         5411                        322                    0                      29.125000               79.231808              1448                   0                      257.666667              492.393271             5.254495e+01  0.386992        2.642759e+06   4.385286e+06  10024910      3             116281383      5.055712e+06  5.005676e+06  10047926     3            116257967      5812898.35    4.941078e+06  10048410     4            4              5              0              0              1              1              764                680                0.206396        0.180596       0                  1448               135.777778          356.064338         126781.813131           1               2               2               9               43              0               0               0               0.875000       135.777778           29.125000             257.666667            0                   0                    0                  4556                4                    4592741            0                    15                 0                    120                29200               1006                4                  20                48633.0      88049.118873  328226      23012       9639209.75  1.321437e+06  10024910  5443180   -1         -1         116281383            BENIGN      1
61066          4                 2                  152                         244                         38                     38                     38.000000               0.000000               122                    122                    122.000000              0.000000               6.484787e+03  98.254348       1.221320e+04   1.671909e+04  30578         3             30584          1.019467e+04  1.765248e+04  30578        3            4              4.00          0.000000e+00  4            4            0              0              0              0              0              0              32                 16                 65.502899       32.751449      38                 122                66.000000           43.377413          1881.600000             0               0               0               0               0               0               0               0               0.500000       66.000000            38.000000             122.000000            152                 4                    4969               0                   0                    0                  0                    25                 0                    40                 0                   0                   3                  8                 0.0          0.000000      0           0           0.00        0.000000e+00  0         0         -1         -1         0                    BENIGN      1
Name: count, Length: 477975, dtype: int64

In [17]:
df_cibseg['Label'] = df_cibseg['Label'].str.strip()
df_cibseg['Label'] = np.where(df_cibseg['Label'] == 'BENIGN', 0, 1)
df_cibseg

,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,Total Length of Bwd Packet,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,...,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,ICMP Code,ICMP Type,Total TCP Flow Time,Label
0,187889,1,1,0,0,0,0,0.000000,0.000000,0,...,0,0,0.00,0.000000e+00,0,0,-1,-1,187889,0
1,187758,1,1,0,0,0,0,0.000000,0.000000,0,...,0,0,0.00,0.000000e+00,0,0,-1,-1,187758,0
2,189882,1,1,0,0,0,0,0.000000,0.000000,0,...,0,0,0.00,0.000000e+00,0,0,-1,-1,189882,0
3,190117,1,1,0,0,0,0,0.000000,0.000000,0,...,0,0,0.00,0.000000e+00,0,0,-1,-1,190117,0
4,188603,1,1,0,0,0,0,0.000000,0.000000,0,...,0,0,0.00,0.000000e+00,0,0,-1,-1,188603,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496636,5074745,7,6,582,1204,582,0,83.142857,219.975323,602,...,0,0,0.00,0.000000e+00,0,0,-1,-1,5074745,0
496637,209,2,2,70,230,35,35,35.000000,0.000000,115,...,0,0,0.00,0.000000e+00,0,0,-1,-1,0,0
496638,116281383,24,21,699,5411,322,0,29.125000,79.231808,1448,...,328226,23012,9639209.75,1.321437e+06,10024910,5443180,-1,-1,116281383,0
496639,149,2,2,72,104,36,36,36.000000,0.000000,52,...,0,0,0.00,0.000000e+00,0,0,-1,-1,0,0
496640,61066,4,2,152,244,38,38,38.000000,0.000000,122,...,0,0,0.00,0.000000e+00,0,0,-1,-1,0,0

In [18]:
df_cibseg['Label'].value_counts()

Label
0    319120
1    177521
Name: count, dtype: int64

# SPLIT

In [19]:
y = df_cibseg['Label']
x = df_cibseg.drop(columns=['Label'])

In [20]:
x_train, x_temp, y_train, y_temp = train_test_split(x, y, test_size = 0.30)

In [21]:
x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, test_size=0.50)

In [22]:
print(x_train.shape)
print(x_val.shape)
print(x_test.shape)

(347648, 81)
(74496, 81)
(74497, 81)

# SCALING

In [23]:
col = list(x_train.columns.values)
print(col)

['Flow Duration', 'Total Fwd Packet', 'Total Bwd packets', 'Total Length of Fwd Packet', 'Total Length of Bwd Packet', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd RST Flags', 'Bwd RST Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Packet Length Min', 'Packet Length Max', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWR Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 'Average Packet Size', 'Fwd Segment Size Avg', 'Bwd Segment Size Avg', 'Fwd Bytes/Bulk Avg', 'Fwd Packet/Bulk Avg', 'Fwd Bulk Rate Avg', 'Bwd Bytes/Bulk Avg', 'Bwd Packet/Bulk Avg', 'Bwd Bulk Rate Avg', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'FWD Init Win Bytes', 'Bwd Init Win Bytes', 'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'ICMP Code', 'ICMP Type', 'Total TCP Flow Time']

In [24]:
col = list(x_val.columns.values)
print(col)

['Flow Duration', 'Total Fwd Packet', 'Total Bwd packets', 'Total Length of Fwd Packet', 'Total Length of Bwd Packet', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd RST Flags', 'Bwd RST Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Packet Length Min', 'Packet Length Max', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWR Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 'Average Packet Size', 'Fwd Segment Size Avg', 'Bwd Segment Size Avg', 'Fwd Bytes/Bulk Avg', 'Fwd Packet/Bulk Avg', 'Fwd Bulk Rate Avg', 'Bwd Bytes/Bulk Avg', 'Bwd Packet/Bulk Avg', 'Bwd Bulk Rate Avg', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'FWD Init Win Bytes', 'Bwd Init Win Bytes', 'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'ICMP Code', 'ICMP Type', 'Total TCP Flow Time']

In [29]:
x_train.replace([np.inf, -np.inf], np.nan, inplace=True)
x_val.replace([np.inf, -np.inf], np.nan, inplace=True)
x_test.replace([np.inf, -np.inf], np.nan, inplace=True)



x_train.fillna(x_train.mean(), inplace=True)
x_val.fillna(x_train.mean(), inplace=True)
x_test.fillna(x_train.mean(), inplace=True)

,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,Total Length of Bwd Packet,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,ICMP Code,ICMP Type,Total TCP Flow Time
99819,160970,8,6,326,11595,326,0,40.750000,115.258405,5792,...,0.0,0,0,0.0,0.0,0,0,-1,-1,160970
47019,5180,7,4,392,11595,392,0,56.000000,148.162073,11595,...,0.0,0,0,0.0,0.0,0,0,-1,-1,678041366
197587,48254,1,1,60,292,60,60,60.000000,0.000000,292,...,0.0,0,0,0.0,0.0,0,0,-1,-1,0
427317,844,2,2,90,210,45,45,45.000000,0.000000,105,...,0.0,0,0,0.0,0.0,0,0,-1,-1,0
247387,211,2,2,84,310,42,42,42.000000,0.000000,155,...,0.0,0,0,0.0,0.0,0,0,-1,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232082,96966,1,1,46,138,46,46,46.000000,0.000000,138,...,0.0,0,0,0.0,0.0,0,0,-1,-1,0
276365,179650,2,2,84,116,42,42,42.000000,0.000000,58,...,0.0,0,0,0.0,0.0,0,0,-1,-1,0
312097,31403638,15,10,879,6713,405,0,58.600000,119.624293,1460,...,0.0,116165,116165,31272298.0,0.0,31272298,31272298,-1,-1,31403638
144859,12987,7,4,381,11595,381,0,54.428571,144.004464,8688,...,0.0,0,0,0.0,0.0,0,0,-1,-1,12987
11053,99999396,2,2,16,0,8,8,8.000000,0.000000,0,...,0.0,90,90,99999221.0,0.0,99999221,99999221,-1,-1,306037554

In [30]:
scaler = StandardScaler()

x_train[col] = scaler.fit_transform(x_train[col])

x_val[col] = scaler.transform(x_val[col])
x_test[col] = scaler.transform(x_test[col])

print(x_train.mean(axis=0).round(2))
print(x_train.std(axis=0).round(2))

Flow Duration                -0.0
Total Fwd Packet             -0.0
Total Bwd packets             0.0
Total Length of Fwd Packet    0.0
Total Length of Bwd Packet   -0.0
                             ...
Idle Max                      0.0
Idle Min                     -0.0
ICMP Code                    -0.0
ICMP Type                     0.0
Total TCP Flow Time          -0.0
Length: 81, dtype: float64
Flow Duration                 1.0
Total Fwd Packet              1.0
Total Bwd packets             1.0
Total Length of Fwd Packet    1.0
Total Length of Bwd Packet    1.0
                             ...
Idle Max                      1.0
Idle Min                      1.0
ICMP Code                     1.0
ICMP Type                     1.0
Total TCP Flow Time           1.0
Length: 81, dtype: float64

# Guardar en varios CSV los datos de Training, Validación y Test

Para que en el pipeline cuando hagamos las fases finales no tenga que pre-procesar los datos todo el tiempo y reduce drásticamente el tiempo de espera

In [31]:
x_train['Label'] = y_train
x_train.to_csv('cs_train.csv', index=False)

In [33]:
x_val['Label'] = y_val
x_val.to_csv('cs_val.csv', index=False)

In [32]:
x_test['Label'] = y_test
x_test.to_csv('cs_test.csv', index=False)